### ISSUE TITLE
syslog_drv fails to build

### ISSUE THREAD

**Issue by mrinalwadhwa** [slashmili/ex_syslogger#8]
If I include `{:ex_syslogger, "~> 1.3"}` in my deps and build, syslog_drv fails to build.

```
===> Compiling syslog
==> ex_syslogger
Compiling 2 files (.ex)
```

Forcing `erlang-syslog` to the latest release that is not on `hex.pm`

```
{:ex_syslogger, "~> 1.3"},
{:syslog, git: "https://github.com/Vagabond/erlang-syslog.git", tag: "1.0.5", override: true}
```
Fixed this for me

```
===> Fetching pc ({git,"git://github.com/blt/port_compiler.git",{tag,"1.6.0"}})
===> Compiling pc
===> Compiling syslog
===> Compiling c_src/syslog_drv.c
===> Linking priv/syslog_drv.so
==> ex_syslogger
Compiling 2 files (.ex)
```

There is an issue on `erlang-syslog` to push the latest release to hex.pm
https://github.com/Vagabond/erlang-syslog/issues/30

In the meantime, it may be wroth depending on the git version.

**Comment by slashmili** [comment]
check out f3963399047af17e038897c69e20d552e6899e1d

**Comment by slashmili** [comment]
BTW I won't be able to publish this package to hex until Vagabond/erlang-syslog#30 is pushed 😞

**Comment by mrinalwadhwa** [comment]
Thank you for the quick fixes.

**Comment by slashmili** [comment]
@mrinalwadhwa no you can point your mix dependancy to hex, the packages are updated in hex
