### ISSUE TITLE
Exception when manually configuring backend level

### ISSUE THREAD

**Issue by smpallen99** [slashmili/ex_syslogger#9]
I get an exception with the following command:

```
iex> Logger.configure_backend {ExSyslogger, :my_syslog}, level: :info
```

The problem is in `ExSyslogger.handle_call({.configure, options?,...`:

```
    {:ok, log} = if config.facility !== new_config.facility or
       config.ident !== new_config.ident or
       config.option !== new_config.option do

        close_log(log)
        open_log(new_config)
    end
```

If the condition fails, the match `{:ok, log} = nil` raises an exception. 

Additionally, I think the `if` statement should includes a check for `level` also.

I'll submit a PR shortly.

**Comment by slashmili** [comment]
@smpallen99 I pulled the changes that you've made and merged it into `master`.  Before I push it to `hex`, can you confirm that it's working for you?

**Comment by slashmili** [comment]
I'd assume it works for you
